spring:
  profiles:
    active: loginPage
  security:
    oauth2:
      client:
        registration:
          github:
            client:
              clientId: 0963e87c05ee82c2db50
              clientSecret: e081456d2df622371cf7402e2f210fa21e474bc5
              userAuthorizationUri: https://github.com/login/oauth/authorize
              accessTokenUri: https://github.com/login/oauth/access_token
              clientAuthenticationScheme: form
            resource:
              userInfoApi: https://api.github.com/user
              repoUri: https://api.github.com/repos
