spring:
  application:
    name: abobik
  profiles:
    active: @spring.profiles.active@
    default: dev

---

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:db
    username: mem
    password: mem
    driver-class-name: org.h2.Driver
  application:
    name: abobik


custom:
  string: Aboba

---

spring:
  profiles: prod
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dbprod
    username: prod
    password: prod


custom:
  string: ProdAboba