spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/javarush_jwt
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

#App properties
app:
  jwtSecret: megaHardSecretKeyUgaBuga
  jwtExpiration: 86400000